In [2]:
import torch
import numpy as np

데이터로 부터 직접 텐서를 생성

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

Numpy 배열로부터 생성

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

다른 텐서로부터 생성

In [5]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tenson: \n{x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor : \n {x_rand} \n")

Ones Tenson: 
tensor([[1, 1],
        [1, 1]])

Random Tensor : 
 tensor([[0.7620, 0.4351],
        [0.4301, 0.2367]]) 



무작위 또는 상수 값을 사용하기

In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor : \n {rand_tensor}\n")
print(f"Ones Tensor : \n {ones_tensor}\n")
print(f"Zeros Tensor : \n {zeros_tensor}\n")

Random Tensor : 
 tensor([[0.3878, 0.1329, 0.3184],
        [0.3856, 0.2558, 0.4239]])

Ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



텐서의 속성(Atrribute)

In [7]:
tensor = torch.rand(3,4)

print(f"Shape of tensor : {tensor.shape}")
print(f"Datatype of tensor : {tensor.dtype}")
print(f"Device tensor is stored in : {tensor.device}")

Shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is stored in : cpu


텐서 연산(Operation)

In [8]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

Numpy식의 표준 인덱싱과 슬라이싱

In [9]:
tensor = torch.ones(4,4)
print('First row:',tensor[0])
print('First column',tensor[:,0])
print('Last column',tensor[...,-1])#...이 있는 건가..?
tensor[:,1]=0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column tensor([1., 1., 1., 1.])
Last column tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


텐서 합치기 tensor.cat


In [11]:
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


산술 연산

헹렬 곱(matrix multiplication)

In [24]:
y1 = tensor @ tensor.T #numpy와 같음
y2 = tensor.matmul(tensor.T)

#rand_like 모양은 같에 random 숫자
y3 = torch.rand_like(tensor)
#out은 y3에 저장하라는 의미
print(y1)
print(y2)
print(y3)
torch.matmul(tensor,tensor.T,out=y3)
print(y3)

tensor([[133., 133., 133., 133.],
        [133., 133., 133., 133.],
        [133., 133., 133., 133.],
        [133., 133., 133., 133.]])
tensor([[133., 133., 133., 133.],
        [133., 133., 133., 133.],
        [133., 133., 133., 133.],
        [133., 133., 133., 133.]])
tensor([[0.8316, 0.1772, 0.4218, 0.9365],
        [0.1124, 0.0736, 0.4364, 0.5286],
        [0.1882, 0.4742, 0.1140, 0.9522],
        [0.1480, 0.6001, 0.4635, 0.5890]])
tensor([[133., 133., 133., 133.],
        [133., 133., 133., 133.],
        [133., 133., 133., 133.],
        [133., 133., 133., 133.]])


요소곱(element-wise)

In [16]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor,out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

단일 요소 (single-element) 텐서의 모든 값을 하나로 집계하여 요소가 하나인 텐서

In [19]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item,type(agg_item))

12.0 <class 'float'>


바꿔치기(in-place) 연산: 연산 결과를 피연산자에 저장하는 연산을 바꿔치기 연산이라고 합니다. _접미사를 가짐.

In [20]:
print(tensor,"\n")
tensor.add_(5) #tensor에 저장이 되도록
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


Numpy 변환 (Bridge) : CPU 상의 텐서와 Numpy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다. => GPU는??

In [21]:
t = torch.ones(5)
print(f"t:{t}")
n = t.numpy()
print(f"n:{n}")

t:tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]


텐서 변경사항이 numpy에 반영이 됨.

In [22]:
t.add_(1)
print(f"t:{t}")
print(f"n:{n}")

t:tensor([2., 2., 2., 2., 2.])
n:[2. 2. 2. 2. 2.]


In [23]:
n = np.ones(5)
t = torch.from_numpy(n)

In [25]:
np.add(n,1,out=n)
print(f"t:{t}")
print(f"n:{n}")

t:tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n:[2. 2. 2. 2. 2.]
